# Generated by Django 4.1.7 on 2023-06-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_test2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='totalquery',
            table='queryTest',
        ),
    ]
