# Generated by Django 4.1.7 on 2023-04-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statusmodel',
            table='status',
        ),
    ]
