# Generated by Django 4.1.7 on 2023-05-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_test', '0003_statusmodel_last_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmodel',
            name='uuid',
        ),
    ]
