# Generated by Django 4.1.7 on 2023-05-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_test', '0004_remove_statusmodel_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='last_value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
