# Generated by Django 4.1.7 on 2023-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('column_en', models.CharField(max_length=100)),
                ('column_kr', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'column_table',
            },
        ),
    ]
