# Generated by Django 4.1.7 on 2023-07-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'query',
            },
        ),
    ]
